@host = http://localhost:3000

### Listar participantes da batalha 1
GET {{host}}/battles/1/contestants

###

### Adicionar gladiador 6 na batalha 1
POST {{host}}/battles/1/contestants
Content-Type: application/json

{
    "gladiatorId": 6
}

###

### Adicionar gladiador 7 na batalha 1
POST {{host}}/battles/1/contestants
Content-Type: application/json

{
    "gladiatorId": 7
}

###

### Remover gladiador 2 da batalha 1
DELETE {{host}}/battles/1/contestants/2