@host = http://localhost:3000

### Usuário inexistente
GET {{host}}/users/9999

###

### Gladiador inexistente
GET {{host}}/gladiators/9999

###

### Batalha inexistente
GET {{host}}/battles/9999

###

### Tentar adicionar gladiador inexistente
POST {{host}}/battles/1/contestants
Content-Type: application/json

{
    "gladiatorId": 9999
}

###

### Tentar adicionar participante duplicado
POST {{host}}/battles/1/contestants
Content-Type: application/json

{
    "gladiatorId": 1
}

###

### Tentar ultrapassar o limite de 5 participantes
POST {{host}}/battles/1/contestants
Content-Type: application/json

{
    "gladiatorId": 10
}