@host = http://localhost:3000

### Listar usuários
GET {{host}}/users

###

### Buscar usuário por ID
GET {{host}}/users/1

###

### Criar usuário
POST {{host}}/users
Content-Type: application/json

{
    "username": "arthur",
    "email": "arthur@email.com"
}

###

### Atualizar usuário
PATCH {{host}}/users/1
Content-Type: application/json

{
    "username": "Arthur Morgan"
}

###

### Remover usuário
DELETE {{host}}/users/1